dexgrasp:
  # DexGraspNet2 network config and checkpoint
  yaml_config: "${paths.repo_root}/third_party/DexGraspNet2/configs/network/train_bimanual_wristfirst.yaml"
  checkpoint: "${paths.repo_root}/third_party/DexGraspNet2/experiments/bidex_mink_wristfirst_full/ckpt/ckpt_50000.pth"
  device: cuda:0
  backbone: sparseconv  # null | pointnet2 | sparseconv | sparse_glob_conv

io:
  save_npz_name: dexgrasp_init.npz

visualization:
  enable: true
  root: "${paths.repo_root}/third_party/DexGraspNet2/visualization"
  object_mesh_root: "${paths.repo_root}/data/sapien_data/preprocessed_meshes/pots"
  ref_scale_dir: "${paths.repo_root}/third_party/DexGraspNet2/experiments/bimanual_full_kp"
  background_color: "#E2F0D9"


